#ifndef IMC_PLATFORM_H
#define IMC_PLATFORM_H

/* Generated by the Vitis standalone platform imported from imc_axi.xsa.
 * Macro spelling differs between BSP/Vitis releases; check xparameters.h
 * after platform generation and add its exact symbol here if needed. */
#include "xparameters.h"

#ifndef IMC_AXI_BASEADDR
#if defined(XPAR_IMC_0_S_AXI_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_IMC_0_S_AXI_BASEADDR
#elif defined(XPAR_IMC_0_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_IMC_0_BASEADDR
#elif defined(XPAR_SYSTEM_IMC_0_S_AXI_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_SYSTEM_IMC_0_S_AXI_BASEADDR
#elif defined(XPAR_IMC_S_AXI_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_IMC_S_AXI_BASEADDR
#elif defined(XPAR_IMC_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_IMC_BASEADDR
#elif defined(XPAR_SYSTEM_IMC_S_AXI_BASEADDR)
#define IMC_AXI_BASEADDR XPAR_SYSTEM_IMC_S_AXI_BASEADDR
#else
#error "Find the generated IMC S_AXI base-address symbol in xparameters.h"
#endif
#endif

#endif
